package com.sinosoft.payment.webservice.pay;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-11T14:37:04.961+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://pay.webservice.payment.sinosoft.com", name = "PayServicePortType")
@XmlSeeAlso({com.sinosoft.payment.webservice.pay.xsd.ObjectFactory.class, ObjectFactory.class})
public interface PayServicePortType {

    @WebResult(name = "return", targetNamespace = "http://pay.webservice.payment.sinosoft.com")
    @Action(input = "urn:payFrom", output = "urn:payFromResponse")
    @RequestWrapper(localName = "payFrom", targetNamespace = "http://pay.webservice.payment.sinosoft.com", className = "com.sinosoft.payment.webservice.pay.PayFrom")
    @WebMethod(action = "urn:payFrom")
    @ResponseWrapper(localName = "payFromResponse", targetNamespace = "http://pay.webservice.payment.sinosoft.com", className = "com.sinosoft.payment.webservice.pay.PayFromResponse")
    public com.sinosoft.payment.webservice.pay.xsd.PayEntity payFrom(
        @WebParam(name = "source", targetNamespace = "http://pay.webservice.payment.sinosoft.com")
        java.lang.String source,
        @WebParam(name = "entity", targetNamespace = "http://pay.webservice.payment.sinosoft.com")
        com.sinosoft.payment.webservice.pay.xsd.PayEntity entity
    );

    @WebResult(name = "return", targetNamespace = "http://pay.webservice.payment.sinosoft.com")
    @Action(input = "urn:pay", output = "urn:payResponse")
    @RequestWrapper(localName = "pay", targetNamespace = "http://pay.webservice.payment.sinosoft.com", className = "com.sinosoft.payment.webservice.pay.Pay")
    @WebMethod(action = "urn:pay")
    @ResponseWrapper(localName = "payResponse", targetNamespace = "http://pay.webservice.payment.sinosoft.com", className = "com.sinosoft.payment.webservice.pay.PayResponse")
    public com.sinosoft.payment.webservice.pay.xsd.PayEntity pay(
        @WebParam(name = "entity", targetNamespace = "http://pay.webservice.payment.sinosoft.com")
        com.sinosoft.payment.webservice.pay.xsd.PayEntity entity
    );

    @WebResult(name = "return", targetNamespace = "http://pay.webservice.payment.sinosoft.com")
    @Action(input = "urn:query", output = "urn:queryResponse")
    @RequestWrapper(localName = "query", targetNamespace = "http://pay.webservice.payment.sinosoft.com", className = "com.sinosoft.payment.webservice.pay.Query")
    @WebMethod(action = "urn:query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://pay.webservice.payment.sinosoft.com", className = "com.sinosoft.payment.webservice.pay.QueryResponse")
    public com.sinosoft.payment.webservice.pay.xsd.PayEntity query(
        @WebParam(name = "entity", targetNamespace = "http://pay.webservice.payment.sinosoft.com")
        com.sinosoft.payment.webservice.pay.xsd.PayEntity entity
    );
}
